/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "packet.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Packet, Packet, 2)


PB_BIND(Placeholder, Placeholder, AUTO)


PB_BIND(Ack, Ack, AUTO)


PB_BIND(EndOfTransmission, EndOfTransmission, AUTO)


PB_BIND(WiFiVector, WiFiVector, 2)


PB_BIND(WiFiData, WiFiData, AUTO)



