[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rust_bridge = { path = "../rust_bridge" }
paste = "1.0.7"
heapless = {version = "0.7.10", features = ["ufmt-impl"] }